// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://thhdjoujpzwtsetrahnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoaGRqb3VqcHp3dHNldHJhaG5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODQ1MTAsImV4cCI6MjA3MTM2MDUxMH0.FXfcWsZuly-UcPPwdiSREK3v4UuLlHed2ftACdebIL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);